INSERT INTO RECEBIMENTO.REMESSA(SEQ_PROTOCOLO, SIG_CLASSE, QTD_VOLUME, QTD_APENSO, TIP_FORMA_RECEBIMENTO, NUM_SEDEX, TIP_STATUS, NUM_REMESSA, NUM_ANO, SIG_RECEBEDOR, DAT_RECEBIMENTO, TIP_PROCESSO, TIP_SIGILO) VALUES
(9015, 'RE', 1, 1, 'SEDEX', 'SR123456789BR', 'PREAUTUACAO', 9015, 2016, 'USUARIO_FALSO', DATE '2016-05-31', 'RECURSAL', 'PUBLICO');

INSERT INTO RECEBIMENTO.REMESSA_PREFERENCIA (SEQ_PROTOCOLO, SEQ_PREFERENCIA) 
VALUES (9015, 3); 