create index RECEBIMENTO.FK_MOTIVO_DEVOLUCAO_DEVO on RECEBIMENTO.DEVOLUCAO (
   SEQ_MOTIVO_DEVOLUCAO ASC
);

create index RECEBIMENTO.FK_MODELO_DEVOLUCAO_DEVO on RECEBIMENTO.DEVOLUCAO (
   SEQ_MODELO_DOCUMENTO ASC
);

create index RECEBIMENTO.FK_CLASSE_PETICIONAVEL_REME on RECEBIMENTO.REMESSA (
   SIG_CLASSE ASC
);